# Name that shows up in the badge
name: Backend

# Trigger workflow on pushes and pull requests to all branches
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g npm@7; cd backend; npm install
  format:
    runs-on: ubuntu-22.04
    name: Prettier format check
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g npm@7; cd backend; npm ci; npm run format:check
